# ConnectEdge Relay Worker — offline encrypted message delivery
name = "connectedge-relay"
main = "relay.ts"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "RELAY_STORE"
id = "cef8f8095d574fa19a1400e26f5df1c9"
